# Generated by Django 5.2.4 on 2025-07-26 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectOverviewReadme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("project_id", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("prompt", models.TextField()),
            ],
        ),
    ]
